<br>
<br>
# Typology D [Banner here]

The exceptionally high percentages of renters—the highest in the study area—distinguish Type D tracts from others. These tracts are in suburban areas such as Bloomington, Eden Prairie, Hopkins, Saint Louis Park, Saint Anthony, Falcon Heights and Lauderdale as well as in urban tracts in St. Paul and Minneapolis. Overall, residents of these census tracts have low median household incomes, which declined during the 2000s but slightly increased during the 2010s. Poverty in D tracts has also been on the high side—third highest in the study area. However, unlike other high-poverty tracts in Type B and A, where poverty rose from 2000 to 2017, poverty rates in Type D tracts remained roughly the same.
<br>
<br>
Type D areas, which have above-average percentages of people of color, continue to become more racially diverse. The percentages of people of color has been increasing rapidly especially in the suburban locations such as Hopkins, St. Louis Park and Eden Prairie. Above-average percentages of residents with limited English proficiency in Type D areas suggest that these areas are home to immigrants. While above-average, however, these percentages are declining. In significant contrast to the rest of the Type D tracts, however, the percentages of residents with limited English proficiency, have been rising in the suburban tracts. This net inflow suggests that Type D tracts in the suburbs are a destination for immigrants.
<br>
<br>
Type D areas also have the lowest percentage of school-age children—nearly half the study area average. The percentage of school-age children are especially low in tracts where college students have a significant presence—mostly in Saint Paul, Minneapolis, Lauderdale and Falcon Heights. However, the percentage of school-age children in suburban tracts is higher compared to the rest of the Type D tracts, demonstrating the larger presence of families with children in the suburban tracts.
<br>
<br>
Housing markets in Type D census tracts have been resilient throughout the recession mostly due to the high percent of renters in Type D areas. While median home values declined in most types during the recession, they remained steady in Type D tracts. Similarly, median home values in these areas has bounced back quicker than other types. Median gross rents, which were relatively affordable compared to the rest of the study area, have been on the rise, after declining between 2000 and 2010. During the 2000s, construction activity in Type D tracts were robust both in the urban and suburban tracts. Since then, new construction declined like it did in the rest of the study area.
Growing racial and cultural diversity can bring changes in the needs of the residents. To meet these needs, cities might, for instance, benefit from offering multicultural services and cultural liaisons to facilitate access to city services. Given the high percentage of rental properties in these areas, robust rental inspection programs can help to ensure a high-quality rental housing stock. Similarly, an emphasis on fair housing resources might help residents of color avoid housing discrimination. First-time homeowner assistance programs could help diversify the housing tenure in these areas.


<iframe src = "https://public.tableau.com/views/D_15726728732890/ClusterG?:embed=y&:display_count=yes&:showVizHome=no!:origin=viz_share_link" width = "100%" height = "600" frameBorder = "0" allowFullScreen />