# Typology G

The racial composition of Type G tracts distinguishes them from all the other types in the study area. These tracts have the lowest percentage of people of color among all types. These areas have experienced the smallest increase in racial and ethnic diversity and have stayed primarily white during the study period. Type G tracts were among the wealthiest, with the highest median incomes in the study area. Despite below-average population growth, the share of residents 65 years or older in Type G tracts increased faster than any other type.
<br>
<br>
Type G tracts have the highest median home values and median gross rents among all types partially because most have exceptional access to natural amenities such as lakes, parks, and other bodies of water. These areas have experienced significant growth during the 1990s and 2000s but since then development has come to a halt like in most other types. 
<br>
<br>
Type G areas might experience a surplus of high-end single-family housing as aging residents eventually downsize. High prices that might suppress demand for housing could also contribute to such a surplus. If residents choose to age in their communities, there may be demand for high-end multifamily housing that is not currently served. Type G tracts could benefit from diversifying their housing stock to better serve the housing needs of their residents. 
<br>
<br>
These census tracts are not likely to have significant development-related challenges other than natural resource protection. For instance, water quality and storm water management are issues that might need to be prioritized. Recreational opportunities as well as programmatic services for older adults might serve the interests of the residents well in these tracts. 
