# Typology F

Type F tracts are mostly located in the exurban parts of the study area. These communities have experienced the fastest growth both in terms of population and home construction since the 1990s. Population in these areas remains on the youngest side of the spectrum; they have some of the highest percentages of school-age children and the lowest percentages of senior residents among all types. The racial makeup of these tracts has remained mostly white despite some increase in racial and ethnic diversity. The tracts also have the second highest median income among all types.
<br>
<br>
Housing markets in these tracts have been very strong. Despite a sharp decline in median home values between 2000 and 2010, housing markets have bounced back rapidly during the 2010s and have remained above the study area average throughout the study period. Type F tracts have some of the lowest percentage of renters among all types and the relative scarcity of rental properties are reflected in high median gross rents—the second highest among all types.  
<br>
<br>
What distinguishes Type F areas from others is the high rate of development—highest in the study area—they have experienced since the 1990s. While development activity slowed somewhat during the 2000s, residential construction in these areas remains above the study area average. Since Type F tracts are among the most recently developed areas, construction activity has taken the form of greenfield development.
<br>
<br>
Keeping up with the infrastructure needs generated by rapid growth is likely to be a challenge for Type F census tracts. These tracts could benefit from strategic and proactive planning of investments in storm water infrastructure, sewer connections, and preservation of natural resources. Planning for active recreational facilities such as practice fields as well as providing youth-oriented programming could help serve the younger population of Type F tracts.
<br>
<br>
Communication and coordination with school districts regarding the siting of new schools could be a vehicle for shaping future growth in Type F tracts. In rapidly growing, younger communities with abundant opportunities for greenfield development, school sites impact not only the location of new housing developments, but also the traffic patterns within the community. It might also be useful to focus on connecting new subdivisions to the rest of the community to ensure street connectivity.
