# Typology C

Banner here

Type C census tracts have historically been white, working-class neighborhoods with an affordable housing stock that has been mostly built between the end of World War II and mid-1970s. These tracts are home to residents with moderate incomes that are slightly below the study area medians. Income trends in these areas resemble the trends in the study area, where median household incomes have finally stabilized after a sharp decline during the 2000s. 
<br>
<br>
Most of the housing stock in these areas comprise single-story, rambler-style homes that make it easier for residents to age in place. So it is not surprising to see that the percentage of residents 65 years or older in these areas is a lot higher than the rest of the study area and is increasing very rapidly. While the total population of these areas has barely changed, its racial composition is noticeably different. These tracts, which have remained predominantly white until the 2000s, has been experiencing a steady inflow of residents of color during the study period. The percentage of people of color in these tracts has exceeded the study area average by the end of the study period.
<br>
<br>
Housing costs in Type C tracts remain below the study area. However, housing market trends in these tracts differ in owner and rental markets. Unlike most of the study area, where median home values have picked up after the recession, median home values in Type C tracts have continued to decline during the 2010s. In rental markets, however, trends in these tracts resemble the study area trends, with median gross rents increasing after the recession, following sharp declines during the 2000s. 
If these trends in declining median home values persist, Type C census tracts might face the risk of deterioration. Maintaining the quality of housing is essential for fending off this risk. Since these census tracts have modest incomes and growing numbers of fixed-income retirees, they might face issues related to deferred maintenance. Housing rehabilitation, maintenance, and weatherization programs might help residents catch up with deferred maintenance and enable home improvements necessary to maintain the quality of housing in Type C tracts.
<br>
<br>
Ensuring the vitality of these census tracts might also require public subsidies that can help stimulate market demand in these areas. For instance, strategic place-making investments that take advantage of growing racial and cultural diversity can boost private investment in Type C tracts. Similarly, supporting and attracting businesses oriented toward the needs of a more racially diverse clientele might not only enhance the economic standing of these areas, but also appeal to the changing preferences of the residents.

<iframe src = "https://public.tableau.com/views/C_15726727831350/ClusterA?:embed=y&:display_count=yes&:showVizHome=no!:origin=viz_share_link" width = "100%" height = "600" frameBorder = "0" allowFullScreen />