<br>
<br>
# Typology E [Banner here]

These are mostly fully developed census tracts with high median home values—second highest after Type D—that has been increasing since 2010 after a sharp decline during the 2000s. While these areas are well-established older communities, they have experienced significant large-scale, high-density infill and redevelopment activity, especially in locations near transportation networks and established and growing job centers. This distinct development pattern has created bifurcated demographic and housing market trends in Type E areas.
<br>
<br>
Established parts of Type E areas with high homeownership rates tend to have old and rapidly aging populations. In fact, Type E areas have the highest percentage of residents 65 years or older and this percentage has increased significantly during the 2010s. Overall, Type E tracts have a highly educated population with some of the highest percentages of residents with bachelor’s and graduate/professional degrees in the study area. These tracts have also been experiencing an influx of residents with graduate/professional degrees.
<br>
<br>
In areas with significant infill and redevelopment projects, demographic and housing market trends have diverged from those in the more fully developed areas. In most of these areas, infill development has been producing increasing numbers of high-density apartment complexes and condos. For example, around the growing job hub along I-394, Golden Valley and parts of Saint Louis Park and the Southdale area in Edina have attracted clusters of large-scale, high-density condominium and apartment projects. Similarly, Roseville has experienced high-density infill development, primarily in the form of senior housing.
<br>
<br>
These high-density properties continue to attract significant numbers of working-age professionals and older adults who are downsizing. The percentages of renters in these areas, which have already been above the study area averages, continue to increase. Median gross rent trends in these areas mirror those in the region mostly because the growing supply of rental units in these areas has lowered the upward pressure on rents.
<br>
<br>
In Type E census tracts, careful planning of large-scale, high-density infill and redevelopment projects offer multiple opportunities for improving the built environment of these tracts. Smooth integration of new projects into the existing fabric of these tracts could be occasions for increasing walkability and enriching the streetscape. Programming for older adults including volunteer opportunities could also be useful to meet the changing needs of residents in Type E tracts.

## Geography

<iframe src = "https://public.tableau.com/views/E_15726731867990/ClusterB?:embed=y&:display_count=yes&:showVizHome=no!:origin=viz_share_link" width = "100%" height = "600" frameBorder = "0" allowFullScreen />
